### ISSUE TITLE
dnsc.h

### ISSUE THREAD

**Issue by kissste** [Cicero-MF/esp_enc28j60#1]
Hello,

I'm trying to compile it and it's missing dnsc.h in user/dhcpc.c 

I have tried googling it, could not find it anywhere.

Could you please add it to github? 

Thank you very much, 
Steve

**Comment by Cicero-MF** [comment]
Hi Kissste (Steve),

The DNS isn't functional yet.  So just comment the include from dhcp.c for now.

I'll add in DNS soon later this month.  Its next on my list.

Thanks for giving it a go.

**Comment by kissste** [comment]
Thank you very much. 
I'm looking forward to a new release, SDK v1.5.0 and whatever else your time allows you to put in.
