### ISSUE TITLE
w5500 & ESP module

### ISSUE THREAD

**Issue by mkeyno** [Cicero-MF/esp_enc28j60#3]
hi @Cicero-MF  and thanks for sharing this elegant job , I'm using ready to use module for both Ethernet and ESP ,and have couple of module with w5500 chip, I was wondering if you have any solution for that , also I've used the Iggor Arduino ESP8266 core lib's , and any interested to make ino sketch so could easily compile and uploaded by Arduino IDE

**Comment by Cicero-MF** [comment]
Thanks @mkeyno.  I like the W5500, at least its a 10/100!  I'll possibly look into it at some point in the next couple of months, but I doubt I'll port to Arduino any time soon.  All my work is in C unfortunately, as are many of the examples.
